env:
  es2021: true
  node: true
extends: "eslint:recommended"
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  babelOptions:
    configFile: "./.babelrc"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - backtick
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  prefer-template:
    - error
  space-in-parens:
    - error
    - always
  no-unused-vars:
    - warn
  space-before-function-paren:
    - error
    - never
  func-call-spacing:
    - error
    - never
  implicit-arrow-linebreak:
    - error
    - beside
  key-spacing:
    - error
    - singleLine:
        afterColon: false
      multiLine:
        afterColon: true
      align:
        on: value
  array-bracket-spacing:
    - error
    - always
  array-bracket-newline:
    - error
    - multiline: true
  array-element-newline:
    - error
    - minItems: 3
  block-spacing:
    - error
