@host= http://localhost:3000

// Ctrl Alt R -> RUN COMMAND SHORTCUT
// Request have Metod in firt line ,
// next comming up headers,
// one line of free spacee
// then put a body for request.

########################### TESTY ##################################
 GET  {{host}}/test
 //authentication: Bearer 0.28995713355807684
 
########################### ALL USERS #################################
 GET  {{host}}/users
######################### REGISTER ################################

POST {{host}}/api/register
Content-Type: application/json

{
    "name":"abcdefghijklmnoprstuw",
    "surname":"1234567890",
    "email":"alphabetDigit@gmail.com",
    "password1":"1234",
    "password2":"1234"
}
######################## LOGIN ##################################
@login = 0.9795861379140136
POST {{host}}/api/login
Content-Type: application/json

{
    "login": {{login}},
    "password":"Ogienwszopie"
}
###################### ME #####################################
@token = 0.9177700965742472
GET {{host}}/api/me
Authentication: Bearer {{token}}
######################## LOGOUT ####################################
GET {{host}}/logout 
Authentication: Bearer {{token}}
######################### Forgot passw ###################################
POST  {{host}}/api/password/remind
Content-Type: application/json

{
    "email":"adam.szr98@gmail.com"
}

#################################################################
@uniqueId = 0.08422863516704693
POST  {{host}}/api/password/reset?code={{uniqueId}}
Content-Type: application/json

{
    "password1":"123",
    "password2":"123",
    "code":{{uniqueId}}

}

#################################################################
GET {{host}}/activate/{{login}}

