@host= http://localhost:3000

// Ctrl Alt R -> RUN COMMAND SHORTCUT
// Request have Metod in firt line ,
// next comming up headers,
// one line of free spacee
// then put a body for request.

########################### TESTY ##################################
 GET  {{host}}/test
 //authentication: Bearer 0.28995713355807684
 
########################### ALL USERS #################################
 GET  {{host}}/users
######################### REGISTER ################################

POST {{host}}/api/register
Content-Type: application/json

{
    "name":"Jastrzab",
    "surname":"Bielik",
    "email":"vofiko7621@28woman.com",
    "password1":"ptak",
    "password2":"ptak"
}
######################## LOGIN ##################################
@login = 0.9938147460824516
POST {{host}}/api/login
Content-Type: application/json

{
    "login": {{login}},
    "password":"123"
}
###################### ME #####################################
@token = 0.7394723770798901
GET {{host}}/api/me
Authentication: Bearer {{token}}
######################## LOGOUT ####################################
GET {{host}}/api/logout 
Authentication: Bearer {{token}}
######################### Forgot passw ###################################
POST  {{host}}/api/password/remind
Content-Type: application/json

{
    "email":"vofiko7621@28woman.com"
}

#################################################################
@uniqueId = 0.6043351227552578
POST  {{host}}/api/password/reset?code={{uniqueId}}
Content-Type: application/json

{
    "password1":"abc123",
    "password2":"abc123",
    "code":{{uniqueId}}

}

#################################################################
GET {{host}}/activate/{{login}}

