 @host= http://localhost:3000


########################### CREATE MEETING ##################################
POST  {{host}}/api/meets
Authentication: Bearer 0.6470534380913802
Content-Type: application/json

{
    "dateStart":"1612256114778",
    "dateEnd":"1612286114778",
    "description":"Spotkanie testowe",
    "externalUrl":"http://localhost:3000",
    "platformId":"1612243314757t5386663959125733r",
    "groupId":"1612243474423t1026935722388651r"
}
// GET Lista grup usera - wszystkie do które należy. /api/groups // header { "authenthication": "string" }
 //   # app.get(`/api/groups`, this.httpHandleMyGroups)

########################### GET ALL MY MEETINGS ##################################
GET  {{host}}/api/meets
Authentication: Bearer 0.1616728942952128
########################### GET PUBLIC MEETINGS #################################
GET {{host}}/api/meets/public
Authentication: Bearer 0.1616728942952128


########################### GET GROUPLESS MEETINGS ##################################
GET {{host}}/api/meets/groupless
Authentication: Bearer 0.6439677917109055

########################### GET MEETING BY GROUP ##################################
GET {{host}}/api/meets/group/1610979779391t8522683242861135r
Authentication: Bearer 0.1616728942952128

########################### GET MEET MEMBERS ##################################
GET {{host}}/api/meets/1612553412215t662636507330461r/users?platformId=1612547061148t45475559048511816r
Authentication: Bearer 0.9631065808061492


########################### GET MEET PERMISSIONS TEMPLATE ##################################
GET {{host}}/api/meets/1612464411661t8492954908030093r/permissions
Authentication: Bearer 0.7616784803603731

########################### GET MEET PERMISSIONS MY ##################################
GET {{host}}/api/meets/1612553412215t662636507330461r/permissions/my
Authentication: Bearer 0.9799054004778651

########################### ADD USERS TO MEETING ##################################
POST  {{host}}/api/meets/1611064137703t8461396525924434r/users
Content-Type: application/json
Authentication: Bearer 0.39873002644713607

{
    "participantsIds": ["222","333","1610979803448t7533778515585501r"]
}

###########################  DELETE USER FROM MEETING  ##################################
DELETE  {{host}}/api/meets/1611047491043t7784219374820294r/users/1610974793354t20544642826315007r
Authentication: Bearer 0.1616728942952128

###########################  DELETE MEET  ##################################
DELETE  {{host}}/api/meets/1611063380189t04053748244075184r
Authentication: Bearer 0.39873002644713607



