 @host= http://localhost:3000

########################### CREATE NEW NOTE ##################################
POST  {{host}}/api/groups/1612547211539t26713156945161565r/notes/
Authentication: Bearer 0.2833669761684472
Content-Type: application/json

{
    "value":"5",
    "userId":"1612547193563t31859588080962276r",
    "description":"5 Giatara "
}

########################### GET MY ALL NOTES ##################################
GET  {{host}}/api/groups/notes?platformId=1612243314757t5386663959125733r&groupId=1612243474423t1026935722388651r
Authentication: Bearer 0.5728065826868913

########################### GET MY NOTES FROM GROUP  ##################################
GET  {{host}}/api/groups/1612243474423t1026935722388651r/notes
Authentication: Bearer 0.27119824505666723


########################### UPDATE NOTE ##################################
PUT  {{host}}/api/groups/notes/1610980874880t02281786304189093r
Authentication: Bearer 0.2503312807869522
Content-Type: application/json

{
    "value":"3",
    "description":"Sprawdzian mnożenie. Po ponownym rozpatrzeniu, nastąpiła zamiana."
}
// Edycja oceny /api/groups/notes/:noteId
// PUT { "authenthication": "string" } // header
//{ // body  "value": "string",  "description": "string",}

########################### DELETE NOTE ##################################
DELETE  {{host}}/api/groups/notes/1611687198655t10614578482302894r
Authentication: Bearer 0.698980472411324


// Skasowanie oceny /api/groups/notes/:noteId
    // { "authenthication": "string" } // header
   // app.delete(`/api/groups/notes/:noteId`, this.httpHandleDeleteNote)

